### ISSUE TITLE
Implement rename_user()

### ISSUE THREAD

**Issue by ThaWeatherman** [ThaWeatherman/trackopy#1]
Find a way to get a user's ID from tb so that renaming can be done.

**Comment by d0mj** [comment]
While not particularly elegant, how about grabbing the raw html from the profile page
`r = requests.get('https://trackobot.com/profile',auth=self._auth)`
and grabbing the ID from the response
`r.text.split('edit_user_',1)[1].split('"')[0]`.

**Comment by ThaWeatherman** [comment]
@d0mj Was already considering that. Didn't do it originally because it isn't very elegant. I wanted to dig around and see if it was exposed any other way, but I don't think it is. I'll most likely add this in the next release along with the query parameter for history().
