### ISSUE TITLE
Extend stats method to return results from a custom time range and filter by game mode.

### ISSUE THREAD

**Issue by d0mj** [ThaWeatherman/trackopy#2]
The API allows for a custom time range to be requested by modifying the endpoint.

`.json?time_range=my_range`

where `my_range` is one of
`[ 'all', 'current_month', 'last_3_days', 'last_24_hours' ]`
or a custom range of the format
`custom&start=YYYY-MM-DD&end=YYYY-MM-DD`.

Similarly one can filter by game mode with
`.json?mode=my_mode`

where `my_mode` is one of 
`[ 'all', 'ranked', 'friendly', 'casual', 'arena' ]`.

Both time range and mode can be requested together e.g.
`https://trackobot.com/profile/stats/classes.json?mode=ranked&time_range=last_3_days`.

**Comment by ThaWeatherman** [comment]
Should be easy enough to add. I might not get to it today but I can have this done soon.

**Comment by ThaWeatherman** [comment]
Was able to do it today. 10 minutes well spent. I'll push this out to Pypi now.
