### ISSUE TITLE
Typo in modify_metadata

### ISSUE THREAD

**Issue by davidjdv** [ThaWeatherman/trackopy#9]
The 'allowed_params' lists '**opponenet**' (instead of 'opponent') which raises the following error when trying to modify this field:

    Error: Invalid value for "-p" / "--param": invalid choice: opponent. (choose from added, mode, win, hero, opponenet, coin, duration, rank, legend, deck_id, opponent_deck_id, note)

**Comment by howdydoody123** [comment]
Good find. I'll make a fix now.
